management:
  server:
      port: 9090
  endpoints:
    web:
      exposure:
        include: "health,info,configprops,env,prometheus,metrics,loggers"
  metrics:
    tags:
      application: jwt-algtest